name: ci

on: [pull_request, push]

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      if: (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && github.event_name == 'push'
      with:
        # Required for `release: merge dev -> master and promote dev`
        token: ${{secrets.GH_TOKEN}}
    - uses: actions/checkout@v4
      if: ((github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && github.event_name == 'push') == false
      with:
        # Required for `release: merge dev -> master and promote dev`
        token: ${{secrets.GH_TOKEN}}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test-with-coverage
    - name: Lint
      run: npm run eslint
    - name: Docker setup - QEMU
      if: (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && github.event_name == 'push'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Docker setup - Buildx
      if: (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')) && github.event_name == 'push'
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: "dev: Docker build"
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      run: |
        docker buildx build \
          --build-arg COMMIT=$(git rev-parse --short HEAD) \
          --platform linux/arm64/v8,linux/386,linux/amd64,linux/arm/v6,linux/arm/v7 \
          -f docker/Dockerfile \
          --provenance=false \
          --push \
          -t koenkk/zigbee2mqtt:latest-dev -t ghcr.io/koenkk/zigbee2mqtt:latest-dev \
          .
    - name: "release: Docker build"
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: |
        TAG="$(git describe --tags)"
        docker buildx build \
          --build-arg COMMIT=$(git rev-parse --short HEAD) \
          --platform linux/arm64/v8,linux/386,linux/amd64,linux/arm/v6,linux/arm/v7 \
          -f docker/Dockerfile \
          --provenance=false \
          --push \
          -t koenkk/zigbee2mqtt:latest -t "koenkk/zigbee2mqtt:$TAG" -t ghcr.io/koenkk/zigbee2mqtt:latest -t "ghcr.io/koenkk/zigbee2mqtt:$TAG" \
          .
    - name: "release: merge dev -> master and promote dev"
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'  
      run: |
        TAG=${GITHUB_REF#refs/*/}
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch --unshallow
        git fetch origin
        git checkout master
        git merge --ff-only origin/dev
        git push origin master
        git checkout dev
        jq ".version = \"$TAG-dev\"" package.json > package.json.tmp
        jq ".version = \"$TAG-dev\"" package-lock.json > package-lock.json.tmp
        mv package.json.tmp package.json
        mv package-lock.json.tmp package-lock.json
        git add -A
        git commit -m "chore: promote to dev"
        git push origin dev

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Install dependencies
        # --ignore-scripts prevents the serialport build which often fails on Windows
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test-with-coverage
